import type { DetectionResponse } from "../types";

function downloadBlob(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function toCsv(rows: DetectionResponse["rows"]): string {
  const h = ["id", "feedback", "label", "confidence", "theme"];
  const esc = (s: string) => `"${String(s).replace(/"/g, '""')}"`;
  const lines = [h.join(",")];
  for (const r of rows) {
    lines.push([esc(r.id), esc(r.feedback), r.label, String(r.confidence), esc(r.theme)].join(","));
  }
  return lines.join("\n");
}

function toMarkdown(res: DetectionResponse): string {
  const { summary } = res;
  return `# Minority detection summary

- Total: **${summary.total}**
- Majority: **${summary.majority}**
- Minority: **${summary.minority}** (${summary.minorityPct}%)
- Needs review: **${summary.needsReview}**

## Top themes — majority
${summary.majorityThemes.map((t) => `- ${t.name}: ${t.count}`).join("\n")}

## Top themes — minority
${summary.minorityThemes.map((t) => `- ${t.name}: ${t.count}`).join("\n")}

_Generated by Student Feedback Minority UI (demo)._
`;
}

type ExportVariant = "light" | "dark";

export function ExportButtons({ result, variant = "light" }: { result: DetectionResponse; variant?: ExportVariant }) {
  const isDark = variant === "dark";
  return (
    <div className="flex flex-wrap items-center gap-2">
      <button
        type="button"
        onClick={() => downloadBlob("labeled_feedback.csv", toCsv(result.rows), "text/csv")}
        className={
          isDark
            ? "inline-flex items-center gap-1.5 rounded-lg border border-white/10 bg-white/[0.06] px-3 py-1.5 text-xs font-semibold text-slate-300 hover:bg-white/[0.1]"
            : "rounded-xl bg-slate-900 px-4 py-2 text-sm font-medium text-white shadow hover:bg-slate-800"
        }
      >
        {isDark && (
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden>
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M7 10l5 5 5-5M12 15V3" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        )}
        Export CSV
      </button>
      <button
        type="button"
        onClick={() => downloadBlob("summary_report.md", toMarkdown(result), "text/markdown")}
        className={
          isDark
            ? "inline-flex rounded-lg border border-white/10 bg-transparent px-3 py-1.5 text-xs font-semibold text-slate-500 hover:border-white/15 hover:text-slate-400"
            : "rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-800 hover:bg-slate-50"
        }
      >
        Summary .md
      </button>
    </div>
  );
}
